name: Publish

on:
  push:
    branches: [main]

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false

      - uses: actions/setup-node@v3
        with:
          node-version: 21.0.0
          cache: yarn

      - name: Install dependencies
        run: |
          yarn install --immutable

      - name: Build
        run: |
          - name: Build
            run: |
              yarn bundle
              sed -i 's/"main": "expo-router\/entry"/"main": "dist\/index.js"/' package.json

      - name: Release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.GH_TOKEN }}

        run: yarn semantic-release
